// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxnGiInekI9FX6f7yUPuwxucYpHrUZWws',
    appId: '1:1061002575810:web:065eec637d0f13339a605b',
    messagingSenderId: '1061002575810',
    projectId: 'smart-fire-detection-272bb',
    authDomain: 'smart-fire-detection-272bb.firebaseapp.com',
    databaseURL: 'https://smart-fire-detection-272bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fire-detection-272bb.firebasestorage.app',
    measurementId: 'G-B05593ZS5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGPqgXRlEnmBRLxxUz-lADNad6fvDNrVk',
    appId: '1:1061002575810:android:0545057f0b9575c39a605b',
    messagingSenderId: '1061002575810',
    projectId: 'smart-fire-detection-272bb',
    databaseURL: 'https://smart-fire-detection-272bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fire-detection-272bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6y5NRSU8eE_nYBAToC7ejqKs0Mt7Se5c',
    appId: '1:1061002575810:ios:4b074f2ad2b144cc9a605b',
    messagingSenderId: '1061002575810',
    projectId: 'smart-fire-detection-272bb',
    databaseURL: 'https://smart-fire-detection-272bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fire-detection-272bb.firebasestorage.app',
    iosBundleId: 'com.fireshield.fireshieldApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6y5NRSU8eE_nYBAToC7ejqKs0Mt7Se5c',
    appId: '1:1061002575810:ios:4b074f2ad2b144cc9a605b',
    messagingSenderId: '1061002575810',
    projectId: 'smart-fire-detection-272bb',
    databaseURL: 'https://smart-fire-detection-272bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fire-detection-272bb.firebasestorage.app',
    iosBundleId: 'com.fireshield.fireshieldApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxnGiInekI9FX6f7yUPuwxucYpHrUZWws',
    appId: '1:1061002575810:web:6fdc111fd27917239a605b',
    messagingSenderId: '1061002575810',
    projectId: 'smart-fire-detection-272bb',
    authDomain: 'smart-fire-detection-272bb.firebaseapp.com',
    databaseURL: 'https://smart-fire-detection-272bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fire-detection-272bb.firebasestorage.app',
    measurementId: 'G-PBNHVWGB3P',
  );
}
